apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: php-bandwidth-iris-location
  description: Links to additional entities in the php-bandwidth-iris repository.
  annotations:
    github.com/project-slug: Bandwidth/php-bandwidth-iris
spec:
  targets:
    - ./component.yaml
